package com.idea.gui;

import javax.swing.*;

/**
 * Created by Devina Ekawati on 5/1/2016.
 */
public class MainPanel extends JPanel {
    private JFrame mainFrame;

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        mainFrame = MainFrame.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        narration = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        friendsPanel = new javax.swing.JPanel();
        playersPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(210, 204, 204));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(41, 48, 74));

        narration.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        narration.setForeground(new java.awt.Color(99, 101, 113));
        narration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        roleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(41, 48, 74));

        friendsPanel.setBackground(new java.awt.Color(210, 204, 204));

        javax.swing.GroupLayout friendsPanelLayout = new javax.swing.GroupLayout(friendsPanel);
        friendsPanel.setLayout(friendsPanelLayout);
        friendsPanelLayout.setHorizontalGroup(
                friendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 452, Short.MAX_VALUE)
        );
        friendsPanelLayout.setVerticalGroup(
                friendsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        playersPanel.setBackground(new java.awt.Color(210, 204, 204));

        javax.swing.GroupLayout playersPanelLayout = new javax.swing.GroupLayout(playersPanel);
        playersPanel.setLayout(playersPanelLayout);
        playersPanelLayout.setHorizontalGroup(
                playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 460, Short.MAX_VALUE)
        );
        playersPanelLayout.setVerticalGroup(
                playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 345, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel)
                                        .addComponent(roleLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(friendsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                                .addComponent(playersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(90, 90, 90))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(narration, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(usernameLabel)
                                .addGap(44, 44, 44)
                                .addComponent(roleLabel)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(playersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(friendsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addComponent(narration, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    public javax.swing.JPanel friendsPanel;
    public javax.swing.JLabel narration;
    public javax.swing.JPanel playersPanel;
    public javax.swing.JLabel roleLabel;
    public javax.swing.JLabel usernameLabel;
    // End of variables declaration
}
