package com.idea.gui;

import javax.swing.*;
import java.awt.Color;

/**
 * Created by Devina Ekawati on 5/1/2016.
 */
public class StartPanel extends JPanel {
    private MainFrame frame;

    /**
     * Creates new form StartGame
     */
    public StartPanel() {
        initComponents();
        frame = MainFrame.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        title = new javax.swing.JLabel();
        ipHostNameLabel = new javax.swing.JLabel();
        ipHostNameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        udpPortLabel = new javax.swing.JLabel();
        servereLabel = new javax.swing.JLabel();
        udpPortTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        serverPortTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(210, 204, 204));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setRequestFocusEnabled(false);

        title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(41, 48, 74));
        title.setText("Werewolf Game");

        ipHostNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ipHostNameLabel.setForeground(new java.awt.Color(75, 86, 106));
        ipHostNameLabel.setText("IP Host Name");

        ipHostNameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ipHostNameTextField.setForeground(new java.awt.Color(75, 86, 106));

        loginButton.setBackground(Color.decode("#636571"));
        loginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginButton.setFocusPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setOpaque(true);
        loginButton.setForeground(Color.WHITE);
        loginButton.setText("Login");

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(75, 86, 106));
        usernameLabel.setText("Username");

        udpPortLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        udpPortLabel.setForeground(new java.awt.Color(75, 86, 106));
        udpPortLabel.setText("UDP Port");

        servereLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        servereLabel.setForeground(new java.awt.Color(75, 86, 106));
        servereLabel.setText("Server Port");

        udpPortTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        udpPortTextField.setForeground(new java.awt.Color(75, 86, 106));

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(75, 86, 106));

        serverPortTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        serverPortTextField.setForeground(new java.awt.Color(75, 86, 106));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(386, 386, 386)
                                                .addComponent(title))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(324, 324, 324)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(loginButton)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(usernameLabel)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(ipHostNameLabel)
                                                                                .addComponent(servereLabel)
                                                                                .addComponent(udpPortLabel))
                                                                        .addGap(32, 32, 32)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(udpPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(ipHostNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(serverPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(title)
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ipHostNameLabel)
                                        .addComponent(ipHostNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(servereLabel)
                                        .addComponent(serverPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(udpPortLabel)
                                        .addComponent(udpPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLabel)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(loginButton)
                                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel ipHostNameLabel;
    public javax.swing.JTextField ipHostNameTextField;
    public javax.swing.JButton loginButton;
    public javax.swing.JTextField serverPortTextField;
    private javax.swing.JLabel servereLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel udpPortLabel;
    public javax.swing.JTextField udpPortTextField;
    private javax.swing.JLabel usernameLabel;
    public javax.swing.JTextField usernameTextField;
    // End of variables declaration
}
