package com.idea.gui;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Devina Ekawati on 5/1/2016.
 */
public class VoteFrame extends JFrame {
    /**
     * Creates new form voteFrame
     */
    public VoteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        okButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vote");
        setBackground(new java.awt.Color(210, 204, 204));

        okButton.setBackground(Color.decode("#636571"));
        okButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        okButton.setForeground(Color.WHITE);
        okButton.setFocusPainted(false);
        okButton.setContentAreaFilled(false);
        okButton.setOpaque(true);
        okButton.setText("OK");

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(75, 86, 106));
        usernameLabel.setText("Username");

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(75, 86, 106));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(okButton)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(usernameLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(114, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLabel)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(okButton)
                                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>

    public javax.swing.JButton okButton;
    private javax.swing.JLabel usernameLabel;
    public javax.swing.JTextField usernameTextField;
}
